{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-robolaunch.serviceAccountName" . }}
  labels:
    {{- include "helm-robolaunch.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-robolaunch.fullname" . }}-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding # created for development environment
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm-robolaunch.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm-robolaunch.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "helm-robolaunch.serviceAccountName" . }}  
    namespace: {{ .Release.Namespace }}
{{- end }}


